//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolBox.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToolBox.Resources.Localization.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu @BagDiameter.
        /// </summary>
        public static string langBagDiameter {
            get {
                return ResourceManager.GetString("langBagDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu @CollectorEfficiency.
        /// </summary>
        public static string langCollectorEfficiency {
            get {
                return ResourceManager.GetString("langCollectorEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu @DefaultModuleName.
        /// </summary>
        public static string langDefaultModuleName {
            get {
                return ResourceManager.GetString("langDefaultModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu @FilterArea.
        /// </summary>
        public static string langFilterArea {
            get {
                return ResourceManager.GetString("langFilterArea", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu @FiltrationArea.
        /// </summary>
        public static string langFiltrationArea {
            get {
                return ResourceManager.GetString("langFiltrationArea", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu @Home.
        /// </summary>
        public static string langHome {
            get {
                return ResourceManager.GetString("langHome", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu @Length.
        /// </summary>
        public static string langLength {
            get {
                return ResourceManager.GetString("langLength", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu @NumberOfFilters.
        /// </summary>
        public static string langNumberOfFilters {
            get {
                return ResourceManager.GetString("langNumberOfFilters", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu @Permeability.
        /// </summary>
        public static string langPermeability {
            get {
                return ResourceManager.GetString("langPermeability", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu @Permeability.
        /// </summary>
        public static string langPermeability2 {
            get {
                return ResourceManager.GetString("langPermeability2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu @Qauntity.
        /// </summary>
        public static string langQuantity {
            get {
                return ResourceManager.GetString("langQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu @ToolTip_01.
        /// </summary>
        public static string langToolTip01 {
            get {
                return ResourceManager.GetString("langToolTip01", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu @ToolTip_02.
        /// </summary>
        public static string langToolTip02 {
            get {
                return ResourceManager.GetString("langToolTip02", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu @ToolTip_03.
        /// </summary>
        public static string langToolTip03 {
            get {
                return ResourceManager.GetString("langToolTip03", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu @ToolTip_04.
        /// </summary>
        public static string langToolTip04 {
            get {
                return ResourceManager.GetString("langToolTip04", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu @ToolTip_05_1.
        /// </summary>
        public static string langToolTip05_1 {
            get {
                return ResourceManager.GetString("langToolTip05_1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu @ToolTip_05_2.
        /// </summary>
        public static string langToolTip05_2 {
            get {
                return ResourceManager.GetString("langToolTip05_2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu @ToolTip_06_1.
        /// </summary>
        public static string langToolTip06_1 {
            get {
                return ResourceManager.GetString("langToolTip06_1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu @ToolTip_06_2.
        /// </summary>
        public static string langToolTip06_2 {
            get {
                return ResourceManager.GetString("langToolTip06_2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu @ToolTip_11.
        /// </summary>
        public static string langToolTip11 {
            get {
                return ResourceManager.GetString("langToolTip11", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu @ToolTip_12.
        /// </summary>
        public static string langToolTip12 {
            get {
                return ResourceManager.GetString("langToolTip12", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu @ToolTip_13.
        /// </summary>
        public static string langToolTip13 {
            get {
                return ResourceManager.GetString("langToolTip13", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu @ToolTip_14.
        /// </summary>
        public static string langToolTip14 {
            get {
                return ResourceManager.GetString("langToolTip14", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu @TotalArea.
        /// </summary>
        public static string langTotalArea {
            get {
                return ResourceManager.GetString("langTotalArea", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu @TotalEfficiency.
        /// </summary>
        public static string langTotalEfficiency {
            get {
                return ResourceManager.GetString("langTotalEfficiency", resourceCulture);
            }
        }
    }
}
